. ~/script/common/unlink.sh
. ~/script/common/link_linux.sh
. ~/script/linux/centos/server.sh
. ~/script/linux/centos/serverconfig.sh
. ~/.bash_profile
. ~/script/linux/centos/ruby.sh
. ~/script/linux/centos/python.sh
. ~/script/linux/centos/perl.sh
. ~/script/linux/centos/nodejs.sh
. ~/script/linux/common/rails.sh
. ~/script/linux/centos/java.sh
. ~/script/common/vim_linux.sh
. ~/js/npm.sh
. ~/js/bower.sh
