sudo mkdir -p ~/work/android
sudo mkdir -p ~/work/ios
sudo mkdir -p ~/work/c++
sudo mkdir -p ~/work/js
sudo mkdir -p ~/work/python
sudo mkdir -p ~/work/ruby
sudo mkdir -p ~/work/scala

ln -s ~/script/common/npm.sh ~/js/
ln -s ~/script/common/bower.sh ~/js/
ln -s ~/script/common/pip.sh ~/python/
ln -s ~/script/dotfiles/.bashrc ~/
ln -s ~/script/dotfiles/.bash_profile ~/
ln -s ~/script/dotfiles/.emmet_snippets_custom.json ~/
ln -s ~/script/dotfiles/.vimrc ~/
ln -s ~/script/dotfiles/.tmux.conf ~/
ln -s ~/script/dotfiles/.gitconfig ~/
ln -s ~/script/dotfiles/.zshrc ~/
ln -s ~/script/dotfiles/.shalias ~/
ln -s ~/script/dotfiles/.zshenv ~/
ln -s ~/script/dotfiles/.bashenv ~/
ln -s ~/script/dotfiles/.commonenv ~/
